<?php
$controller = strtolower($controller);
$action = strtolower($action);
$t = time();
switch ($controller) {
	case 'adminlogin':
		switch ($action) {
            case 'login':
				 $this->headScript()
				    ->prependFile($this->basePath() . '/js/backend/adminlogin.js?version='.$t);
            break;
         }
    break;
    case 'usermanage':
        switch($action) {
            case 'userdetails':
                 $this->headScript()
//                ->prependFile($this->basePath() . '/js/admin/jquery.js')
//                ->prependFile($this->basePath() . '/js/admin/jquery.validate.min.js')
                ->prependFile($this->basePath() . '/js/backend/csvdownload.js')
                ->prependFile($this->basePath() . '/js/backend/useredit.js')
				->prependFile($this->basePath() . '/js/backend/search-user.js')
				->prependFile($this->basePath() . '/js/backend/sorttable.js');
            break;
            case 'useredit':
                 $this->headScript()
                ->prependFile($this->basePath() . '/js/backend/useredit.js');
            break;
            case 'userbackupdet':
                 $this->headScript()
                ->prependFile($this->basePath() . '/js/backend/useredit.js')
                ->prependFile($this->basePath() . '/js/backend/sorttable.js');
            break;
        }
    break;
    case 'uploads':
        switch($action) {
            case 'view':
                 $this->headScript()
                ->prependFile($this->basePath() . '/js/backend/delupload.js');
            break;
        }
    break;
    case 'seomanage':
        switch($action) {
            case 'editseo':
                 $this->headScript()
                ->prependFile($this->basePath() . '/js/backend/seo.js');
            break;
            case 'bgedit':
                 $this->headScript()
                ->prependFile($this->basePath() . '/js/backend/bgimg.js');
            break;
        }
    break;

	default:
		break;
}
echo $this->headScript()
    ->prependFile($this->basePath() . '/js/jquery/jquery.form.js?version='.$t)
    ->prependFile($this->basePath() . '/js/backend/logout.popup.js?version='.$t)
    ->prependFile($this->basePath() . '/js/backend/common-scripts.js?version='.$t)
    ->prependFile($this->basePath() . '/js/backend/jquery.nicescroll.js')
//    ->prependFile($this->basePath() . '/js/admin/jquery.dcjqaccordion.2.7.js')
//    ->prependFile($this->basePath() . '/js/bootstrap/bootstrap.min.js')
    ->prependFile('//code.jquery.com/ui/1.9.2/jquery-ui.js')
    ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js');
?>
