<?php
$controller = strtolower($controller);
$action = strtolower($action);
$t = time();
switch ($controller) {
//    case 'userregistration':
//        switch ($action) {
//             case 'userdetails':
//                $this->headLink()
//                    ->prependStylesheet($this->basePath() . '/css/admin/useredit.css?version='.$t)
//				    ->prependStylesheet('//code.jquery.com/ui/1.9.1/themes/base/jquery-ui.css');
//                break;
//            case 'useredit':
//                $this->headLink()
//                    ->prependStylesheet($this->basePath() . '/css/admin/useredit.css?version='.$t)
//				    ->prependStylesheet('//code.jquery.com/ui/1.9.1/themes/base/jquery-ui.css');
//                break;
//		}
//		break;
//    case 'sectionmanage':
//		switch ($action) {
//            case 'editsection':
//				 $this->headLink()
//                        ->prependStylesheet('//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css');
//            break;
//            case 'addsection':
//				 $this->headLink()
//                        ->prependStylesheet('//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css');
//            break;
//		    }
	default:
		break;
}
echo $this->headLink()
->prependStylesheet('//fonts.googleapis.com/css?family=Ruda:400,700,900')
->prependStylesheet($this->basePath() . '/css/backend/style_temp.css?version='.$t)
->prependStylesheet($this->basePath() . '/css/backend/style.css?version='.$t)
->prependStylesheet('//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css')
->prependStylesheet($this->basePath() . '/css/bootstrap/bootstrap.css');
?>
