<aside>
	<div id="sidebar" class="nav-collapse ">
		<!-- sidebar menu start-->
		<ul class="sidebar-menu" id="nav-accordion">
			<p class="centered">
				<a class='logo_class'><img src="../../image/backend/user.png"
					class="img-circle" width="60">
				</a>
			</p>
			<h5 class="centered">
				<?php echo "Admin"?></h5>

			<li class='usermanage common_class'><a title="Details of Emmortal Users"
				class="common_class usermanage"> <i class="fa fa-user"></i> <span>User management</span>
			</a></li>
			<li class='seomanage common_class'><a title="Details of Emmortal SEO"
				class="common_class seomanage"> <i class="fa fa-area-chart"></i> <span>SEO management</span>
			</a></li>
            <li class='uploads common_class'><a title="Details of Emmortal Uploads"
				class="common_class uploads"> <i class="fa fa-cloud-upload"></i> <span>Upload management</span>
			</a></li>

        <!-- sidebar menu end-->
        </ul>
	</div>
</aside>
