<!-- <div class="main_section">
			
            
		     <div class="termsBody">
                <p class="moodal-text inner_content"></p>
		  </div> 
</div> create newpassword modal -->
<div class="modal fade" id="squarespaceModalchangeimage" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog modal-box signin_popup">
  <div class="modal-content modal-outer">
    <div class="modal-header modal-headernew">
      <button type="button" class="close close-new" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
      <h3 class="modal-title" id="lineModalLabel">Upload your profile photo and background</h3>
    </div>
    <div class="modal-body">
      
            <!-- content goes here -->
    <div>
    <div class="" >
     <form action="/image/saveimage" method="post" enctype="multipart/form-data" name="form1" id="imageuploadform">
                        <div class="aviary-div">
                           
                              <div class="image-form-field " picture-name="photo" height="360" field-name="image"></div>
                              <div class="image-select">
                                 <div class="img-input">
                                    <div class="canvas-placeholder" style="height: 120px; width: 360px;">
                                       <i class="fa fa-picture-o remove-fa-picture-icon"></i>
                                       <!--<img id= 'profile_pic_thumb'/>-->
                                    </div>
                                    <div class="btn e-btn btn-primary file-input-btn" style="width: 360px;">
                                       <i class="fa fa-upload"></i>
                                       Choose photo
                                       <input name="file" type="file" id="imageArea1">
                                       <input type = "hidden" id = "imagePath" value="">
                                       <input type = "hidden" id= "aviaryPath" name= "action" value="">
                                    </div>
                                    <span id="imagePathError" style="color:red;display:none;">No image Selected</span>
                                 </div>
                              </div>
                           </div>
                        
                     </form>
                     </div>
                    
                     <div class="">
                     <form action="/image/saveimage" method="post" enctype="multipart/form-data" name="form1" id="imageuploadform">
                        <div class="aviary-div">
                           <div class="" >
                              <div class="image-form-field " picture-name="photo" height="360" field-name="image"></div>
                              <div class="image-select">
                                 <div class="img-input">
                                    <div class="canvas-placeholder" style="height: 120px; width: 360px;">
                                       <i class="fa fa-picture-o remove-fa-picture-icon"></i>
                                       <!--<img id= 'profile_pic_thumb'/>-->
                                    </div>
                                    <div class="btn e-btn btn-primary file-input-btn" style="width: 360px;" >
                                       <i class="fa fa-upload"></i>
                                       Choose photo
                                       <input name="file" type="file" id="imageArea1">
                                       <input type = "hidden" id = "imagePath" value="">
                                       <input type = "hidden" id= "aviaryPath" name= "action" value="">
                                    </div>
                                    <span id="imagePathError" style="color:red;display:none;">No image Selected</span>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </form>
                     </div>
            <div class="modal-footersec">
                <span class="">
               <button type="button" class="btn e-btn btn-default" onclick="$('.close').trigger('click');" data-toggle="modal" data-target="#uploadModal">skip</button>
               <button type="submit" class="btn e-btn btn-primary" id = "saveimageDetails">save</button>
               </span>
            </div>
    </div>
  </div>
  </div>
</div>