<section id="main-content">
	<section class="wrapper">
		<h3 style="text-align:center;">
			Emmortal Upload Details
		</h3>
		<div class="col-sm-12"
			style="margin-bottom: 20px; padding: 0 !important">

			<h1 id="csv_title" style="display: none;">Emmortal Upload Details</h1>
<!--				<a href="/usermanage/uploadbackup" class="user_backup" title="Upload backup details"><i class="fa fa-recycle fa-3x" aria-hidden="true"></i></a>-->


		</div>

		<div class="row mt">
			<div class="col-md-12">
				<div class="content-panel" style="padding-top: 5px;">

				       <div class="col-md-12" style="padding: 0px 10px;">
                            <!-- No. of Uploads here -->
                            <div class="numberclasscheck" style="margin-bottom: 10px">Number Of Upload(s) :
                                <?php if(!empty($uploaddata)){
								    $num = count($uploaddata);
                                    echo $num;  } ?>
                            </div>
                            <!-- No. of Uploads end -->
                       </div>
                        <table class="table table-striped table-advance table-hover tbody uploadDetails datatable sortable" name="uploadDetails" id="uploadDetails">

						<thead>
							<tr class="show_rows">
								<td style="cursor: pointer; font-weight: bold;" class="hidden-phone"><i
									class="fa fa-bookmark"></i> Title</td>
								<td style="cursor: pointer; font-weight: bold;" class="hidden-phone"><i
									class="fa fa-bookmark"></i> Description</td>
                                <td style="cursor: pointer; font-weight: bold;" class="hidden-phone"><i
									class="fa fa-bookmark"></i> Upload Path</td>
                                <td style="cursor: pointer; font-weight: bold;"><i
									class="fa fa-bookmark"></i> Type</td>
								<td style="cursor: pointer; font-weight: bold;"><i
									class="fa fa-bookmark"></i> Time of Upload</td>
                                <td style="cursor: pointer; font-weight: bold;" class="sorttable_nosort"><i
									class="fa fa-bookmark"></i> Action</td>
							</tr>
						</thead>

						<tbody class="my_size">
							<?php if(!empty($uploaddata)){
								foreach($uploaddata as $key => $val)
					               { ?>

							<tr	class="manageAll catId show_rows">
								<td class="hidden-phone"><?php if(!empty($val['uploadTitle'])){
                                    echo strip_tags($val['uploadTitle']);} else{ echo "N/A"; }
                                    ?></td>
								<td class="hidden-phone email-width"><span class=""
									style=""><?php echo strip_tags($val['uploadDescription']); ?>
								</span></td>
                                <td class="hidden-phone uploadPath">
                                    <?php if(($val['uploadType'] == "image") || ($val['uploadType'] == "video")){ ?><span class="uploadPath" style="padding: 5px; font-weight: bold;"><?php if (@getimagesize($val['uploadPath'])) { ?><img src="<?php echo $val['uploadPath'] ?>"  height="100px" width="100px" /><?php }else{ ?><i class='fa fa-picture-o' aria-hidden='true' style="font-size: 5em;"></i><?php } ?>

								    </span> <?php } else{?>
                                    <span class="uploadPath"><div style="margin-left: 5px; height: 100px; width: 100px;font-size: 10px;font-weight: bold; border: 1px solid lightgray; background-color: #fff; color: #726971 !important; overflow: hidden; padding-left: 5px;"><?php echo strip_tags($val['uploadTitle'])."<br/>"."<br/>".strip_tags($val['uploadDescription']);?></div></span><?php }?>
                                </td>
                                <td class="hidden-phone"><span class=""
									style="width: 80%; display: inline-block;"><?php echo $val['uploadType'];?>
								</span></td>
                                <td class="hidden-phone"><span class=""
									style="width: 80%; display: inline-block;"><?php echo $val['TimeStamp'];?>
								</span></td>

								<input type="hidden"  class="hidden_class" value="<?php echo $val['uploadId']; ?>" />
								<td class="sorttable_nosort">
									        <button class="btn btn-danger btn-xs dlt_nom delUpload" title="Delete upload">
										        <i class="fa fa-trash-o"></i>
									        </button> <br/>
								</td>
							</tr>
							<tr id="hidden_tr" style="display: none;" class="for_search">
								<th style="border-bottom: 0px !important;">No records found</th>
							</tr>
							<?php }
                            }
							else
							{
							   echo "No records found...";
							}?>
						</tbody>
					</table>
				</div>
				<!-- /content-panel -->

			</div>
			<!-- /col-md-12 -->
		</div>
		<!-- /row -->

	</section>
	<!-- /wrapper -->

	<!--delete popup -->
	<section id="dynamicdeluploadpopup" class="popupFormForDynamicPage chang_PPopup_conta">
	 <div id="" class="chang_PPopup">
     <div class="tab-content" style="border:0px solid;width:490px;">
		<form class="form-popup" style="margin-top: 0px;" method="POST" action="/uploads/delupload" enctype="multipart/form-data">
			 <a class="close" href="javascript:void(0)" onclick="$('#dynamicdeluploadpopup').hide();" style="margin: 10px 10px 0 0px;"><i aria-hidden="true" class="fa fa-times"></i></a>
			<h2 class="form-login-heading">Delete Upload</h2>
			<div class="login-wrap" style="overflow:hidden;text-align:center;">
				<input type="hidden" name="hidden_upid" id="hidden_uploadid" class="hidden_upid" />
				<h4 class="form-login-heading">Are you sure you want to delete this upload?</h4>
				<div style="overflow:hidden;display:inline-block;">
                    <input type="button" class="popup_cancel" onclick="$('#dynamicdeluploadpopup').hide();" id="btn" value="CANCEL"/>
                    <input type="submit" class="popup_cancel" id="delUpload" value="OK"/>
				</div>
			</div>
		</form>
     </div><!--/tab-content-->
     </div>
    </section><!-- /delete popup-->

</section>
<!-- /MAIN CONTENT -->
