<section class="setting-contant">
        <div class="container">
            <div class="inner-contant">
                <div class="tab">
                    <h2>Settings</h2>
                    <button class="tablinks" onclick="openCity(event, 'gen')" id="defaultOpen">General</button>
                    <button class="tablinks" onclick="openCity(event, 'security')">Security</button>
                    <button class="tablinks" onclick="openCity(event, 'perchase')">Purchasing</button>
                    <button class="tablinks" onclick="openCity(event, 'Privacy')" id="defaultOpen">Privacy</button>
                    <button class="tablinks" onclick="openCity(event, 'support')">Support</button>
                </div>
                <div>
                    <div id="gen" class="tabcontent">
                        <div class="col-lg-6">
                            <h3>Personal information</h3>
                            <form action="/action_page.php">
                                <input class="gen-input" type="text" name="fname" placeholder="First name">
                                <input class="gen-input" type="text" name="lname" placeholder="Last name">
                                <input class="gen-input-mail" type="text" name="lname" placeholder="E-mail">
                                <input type="text" class="form-control " id="exampleInputPassword1" placeholder="">
                                <div class="picker-icon"><i class="fa fa-calendar" aria-hidden="true"></i></div>
                            </form>
                        </div>
                        <div class="col-lg-6">
                            <div class="col-lg-6 no-padding">
                                <img class="right-contant" src="/image/img444.jpg" />
                                <a class="avatar" href="#">Choose avatar</a>
                            </div>
                            <div class="col-lg-6 no-padding">
                                <img class="right-contant" src="/image/img444.jpg" />
                                <a class="avatar" href="#">Choose avatar</a>
                            </div>
                            <a class="save" href="#">Save</a>
                        </div>


                    </div>
                    <div id="security" class="tabcontent">
                        <div class="col-lg-12">
                            <h3>Change password</h3>
                            <form action="/action_page.php">
                                <input type="password" class="form-control " id="exampleInputPassword1" placeholder="Current password">
                                <input type="password" class="form-control " id="exampleInputPassword1" placeholder="New password">
                                <input type="password" class="form-control " id="exampleInputPassword1" placeholder="Password confirmation">
                            </form>
                            <a class="save-new" href="#">Save</a>
                            <div>
                                <hr>
                            </div>
                        </div>

                    </div>

                    <div id="perchase" class="tabcontent">
                        <h3>Purchasing</h3>

                    </div>
                    <div id="Privacy" class="tabcontent">
                        <div class="col-lg-6">
                            <h3>Privacy settings</h3>
                            <p class="sub-text">Who can see my Emmortal profile?</p>
                            <div class="dropdown">
                                <button class="btn btn-primary dropdown-toggle drop-down" type="button" data-toggle="dropdown">For All
                                    <span class="caret drop-icon"></span></button>
                                <ul class="dropdown-menu">
                                    <li><a href="#">For AllL</a></li>
                                    <li><a href="#">For Friend</a></li>
                                </ul>
                            </div>
                            <br>
                            <p class="sub-text">Who can find me?</p>
                            <div class="dropdown">
                                <button class="btn btn-primary dropdown-toggle drop-down" type="button" data-toggle="dropdown">For All
                                    <span class="caret drop-icon"></span></button>
                                <ul class="dropdown-menu">
                                    <li><a href="#">For AllL</a></li>
                                    <li><a href="#">For Friend</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="right-area">
                                <p class="sub-text">Content</p>
                                <form action="/action_page.php" method="get">
                                    <input type="checkbox" name="" value=""> Place all Tributes on my page automatically
                                    <br>
                                    <input type="checkbox" name="" value="" checked>Place all new content on my page automatically
                                    <br>

                                </form>
                            </div>
                        </div>
                    </div>
                    <div id="support" class="tabcontent">
                        <div class="col-lg-7">
                            <h3>Send us your question</h3>
                            <textarea rows="4" cols="50">

                            </textarea>
                            <a class="save-new" href="#">Send</a>
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </section>
