<section class="setting-contant">
    <div class="container" id="totalwrapcontainer">
        <div class="inner-contant">
            <div class="tab">
                <h2>Settings</h2>
                <button class="tablinks" onclick="openCity(event, 'gen')" id="defaultOpen">General</button>
                <button class="tablinks" onclick="openCity(event, 'security')">Security</button>
                <!--<button class="tablinks" onclick="openCity(event, 'perchase')">Purchasing</button>-->
                <button class="tablinks" onclick="openCity(event, 'Privacy')" id="defaultOpen">Privacy</button>
                <button class="tablinks" onclick="openCity(event, 'support')">Support</button>
            </div>
            <div>
                <div id="gen" class="tabcontent  profileDetails">
                    <div class="col-lg-6">
                        <h3>Personal information</h3>
                        <form action="/action_page.php">
                            <input class="gen-input" type="text" name="fname" id="acc-name" value="<?php echo $userDetails[0]['firstname'];?>">
                            <input class="gen-input" id="acc-lastname" type="text" name="lname" value="<?php echo $userDetails[0]['lastname'];?>">
                            <input class="gen-input-mail" id="acc-email" type="text" name="email" value="<?php echo $userDetails[0]['emailid'];?>">
                            
                            <div class="form-group full-width" >
                                <div class='input-group date' id='datetimepicker1'>
                                    <input type='text' class="form-control" id="acc-dob" value="<?php echo $userDetails[0]['dateofbirth'];?>">
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>
                            </div>
                            
                            
                            <!--<div class="picker-icon"><i class="fa fa-calendar" aria-hidden="true"></i></div>-->
                        </form>
                        <span class="div--error_secondmsg" style="margin: 20px 0 !important;"></span>
                    </div>
                    <div class="col-lg-6">
                        <div class="col-lg-6 no-padding">
                            <form action="/account/profileimage" method="post" enctype="multipart/form-data" name="profileimagechangeform" id="profileimagechangeform" style="padding-top: 70px;">
                            
                                <div class="img-input">
                                    <div class="canvas-placeholder" id="canvas-placeholderpfimage" style="height: 134px; width: 176px;">
                                        <?php if(@getimagesize($userDetails[0]['profileimage'])){ ?>
                                        <img src="<?php echo $userDetails[0]['profileimage'];?>" style="height:120px; width:160px;" >
                                        <?php }else{ ?>
                                        <i class="fa fa-picture-o remove-fa-picture-icon" style="height:120px; width:160px;"></i><?php } ?>
                                    </div>
                                    <div id="reloaddiv" style=" width: 176px;">
                                        <?php if(@getimagesize($userDetails[0]['profileimage'])){ ?>
                                        <div class="btn e-btn btn-primary file-input-btn removeavtr" id="removeavtr">
                                            <i class="fa fa-times-circle"></i>
                                            Remove avatar
                                            <?php }else{ ?>
                                            <div class="btn e-btn btn-primary file-input-btn" >
                                                <i class="fa fa-upload"></i>
                                                Choose avatar
                                                <input name="profileimage" type="file" id="profileimagechange"> 
                                                <?php } ?>
                                                <input type = "hidden" id = "pfimagePath" value="">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6 no-padding"  style="margin-top: 69px;">
                                    <div class="img-input">
                                        <div class="canvas-placeholder" id="canvas-placeholderbkimage" style="height: 134px; width: 176px;">
                                            <?php if(@getimagesize($userDetails[0]['backgroundimage'])){ ?>
                                            <img src="<?php echo $userDetails[0]['backgroundimage'];?>" style="height:120px; width:100%;" >
                                            <?php }else{ ?>
                                            <i class="fa fa-picture-o remove-fa-picture-icon" style="height:120px; width:160px;"></i><?php } ?>
                                        </div>
                                        <input type="hidden" id="imgSrc" name="imgSrc" />
                                        <div id="reloaddivbk" style=" width: 176px;">

                                            <?php if(@getimagesize($userDetails[0]['backgroundimage'])){ ?>
                                            <div class="btn e-btn btn-primary file-input-btn removeavtr" id="removebgavtr">
                                                <i class="fa fa-times-circle"></i>
                                            Remove Background<?php }else{ ?>
                                                <div class="btn e-btn btn-primary file-input-btn bgimageBtn" id="bgimageBtn" data-toggle="modal" data-target="#myModal">
                                                    <i class="fa fa-upload"></i>
<!--                                                    <button type="button" class="modBtn" id="modBtn" data-toggle="modal" data-target="#myModal">Choose Background</button>-->
                                            Choose Background
<!--                                                  <input name="backgroundimage" type="file" id="backgroundimagechange">-->
                                                    <?php } ?>
                                                    <input type = "hidden" id = "bkimagePath" value="">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                        </form>
                        <a class="save" id="changePersonalDetails" href="javascript:void(0)" disabled="disabled" style="cursor:pointer;">Save</a>
                    </div>
                </div>
                <div id="security" class="tabcontent ">
                    <div class="col-lg-12">
                        <h3>Change password</h3>
                        <form method="post" action="/settings/changepassword" enctype="multipart/form-data" id="form__changepassword">
                            <input type="password" class="form-control passwordDetails" id="acc-cur-pass" placeholder="Current password">
                            <span id = "currentpassError" class='error'>Is invalid</span>
                            <input type="password" class="form-control passwordDetails" id="acc-pass" placeholder="New password">
                            <input type="password" class="form-control passwordDetails" id="acc-pass-rep" placeholder="Password confirmation">
                            <span id = "confirmpassError" class='error'>doesn't match Password</span>
                        </form>
                        <a class="save-new" href="javascript:void(0)" id="password_save" disabled="disabled" style="cursor:not-allowed;">Save</a>
                        <span class="div--error_secondmsg" style="margin: 20px 0 !important;"></span>
                        <!--<div>
                            <hr>
                        </div>-->
                    </div>
                </div>
                <!--<div id="perchase" class="tabcontent">
                        <h3>Purchasing</h3>
                </div>-->
                <div id="Privacy" class="tabcontent">
                    <div class="col-lg-6">
                        <h3>Privacy settings</h3>
                        <p class="sub-text">Who can see my Emmortal profile?</p>
                        <div class="dropdown">
                            <select name="AID" id="profileView" class="drop dropdown-toggle drop-down "  data-toggle="dropdown">
                                <option value="0" <?php if($userDetails[0]['viewprofile'] == 0){echo "selected"; }?>>For All</option>
                                <option value="1" <?php if($userDetails[0]['viewprofile'] == 1){echo "selected"; }?>>For Friend</option>
                            </select>
                            <!--<button class="btn btn-primary dropdown-toggle drop-down" type="button" data-toggle="dropdown">For All
                            <span class="caret drop-icon"></span>
                            </button>-->
                            <!--<ul class="dropdown-menu">
                            <li><a href="javascript:void(0)">For All</a></li>
                            <li><a href="javascript:void(0)">For Friend</a></li>
                            </ul>-->
                        </div>
                        <br>
                        <p class="sub-text">Who can find me?</p>
                        <div class="dropdown">
                            <select name="AID" id="nameView" class="drop dropdown-toggle drop-down "  data-toggle="dropdown">
                                <option value="0" <?php if($userDetails[0]['viewname'] == 0){echo "selected"; }?>>For All</option>
                                <option value="1" <?php if($userDetails[0]['viewname'] == 1){echo "selected"; }?>>For Friend</option>
                            </select>   
                            <!--<button class="btn btn-primary dropdown-toggle drop-down" type="button" data-toggle="dropdown">For All
                            <span class="caret drop-icon"></span></button>
                            <ul class="dropdown-menu">
                            <li><a href="javascript:void(0)">For AllL</a></li>
                            <li><a href="javascript:void(0)">For Friend</a></li>
                            </ul>-->
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="right-area">
                            <p class="sub-text">Content</p>
                            <form action="/action_page.php" method="get">
                                <input type="checkbox" name="" value=""> Place all Tributes on my page automatically
                                <br>
                                <input type="checkbox" name="" value="" checked>Place all new content on my page automatically
                                <br>
                            </form>
                        </div>
                    </div>
                </div>
                <div id="support" class="tabcontent supportQues">
                    <div class="col-lg-7">
                        <h3>Send us your question</h3>
                        <textarea rows="4" cols="50" id="questionDetails"></textarea>
                        <button class="save-new" href="javascript:void(0)" id="saveQuestion" disabled="disabled" style="cursor:not-allowed;">Send</button>
                        <span class="div--error_secondmsg" style="margin: 20px 0 !important;"></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>

 <!--modal (start)-->
    <!-- Modal -->
<div class="modal fade" id="myModal"  role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>

                </button>
                 <h4 class="modal-title" id="myModalLabel">Choose Image</h4>

            </div>
            <div class="modal-body">
                <div role="tabpanel">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active" id="upload"><a href="#uploadTab" aria-controls="uploadTab" role="tab" data-toggle="tab">MY IMAGES</a>

                        </li>
                        <li role="presentation" id="browse"><a href="#browseTab" aria-controls="browseTab" role="tab" data-toggle="tab">PATTERNS</a>

                        </li>
                    </ul>
                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane active uploadTab" id="uploadTab">
                          <div class="col-md-12">
<!--                            <div class="col-sm-12">-->
                                <div class="col-md-6">
                                    <label class="uploadbtn">Upload Image</label>
                                    <form class="form-login reg-form" id='imgUploadForm' name="imgUploadForm" method="post" action="/settings/bgeditsubmit" enctype="multipart/form-data">
                                        <input type="file" class="form-control uploadbtn-input-file" name="fileupload" id="fileupload" style='height: 30%;' required />
                                     </form>
                                </div>
                                <div id="img_prev" class="img_prev col-md-6" style="padding-left: 60px;">
                                    <?php if(!empty($bgimg[0]['bgimgpath'])){ ?>
                                    <img class="imgPrev" id="imgPrev" src="<?php echo $bgimg[0]['bgimgpath'] ?>" onerror="this.src='/image/profile-deafult-avatar.jpg'" height="100px" width="100px" style="margin: 5px 12em 0 0;" />
									<?php } else{ ?><img class="imgPrev" id="imgPrev" src="" onerror="this.src='/image/profile-deafult-avatar.jpg'" height="100px" width="100px" style="margin-top: 5px;" />
                                 <?php }?>
                                 </div>
                                    <label id="errorImg1" class="col-md-6" style="top: 15px;"></label><!--img extnsn valid-->
<!--                                    style="margin-left: 10px;"-->
                                    <label id="errorImg2" class="col-md-6" style="top: 15px;"></label><!--img size(>1MB) valid-->
                                    <!-- style="margin-left: 70px;"-->

<!--

                                </div>
-->
                              <div class="col-sm-12" class="savedImg" id="savedImg" style="margin: 10px 0 0px -45px;"></div>
                            </div><!--/col-md-12-->

                            <div class="col-sm-4"></div>
                          </div><!-- /col-md-12 -->
                        </div><!-- /uploadTab -->

                        <div role="tabpanel" class="tab-pane col-sm-12 browseTab" id="browseTab">
                        <div class="imgAppend" id="imgAppend"></div>
                        </div>
                   </div>
                </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary save" data-dismiss="modal">Save changes</button>
            </div>
        </div>
    </div>
</div>
   <!--modal (end)-->

