<?php

$controller = strtolower($controller);
$action = strtolower($action);
$t = time();
switch ($controller) {
    case 'album':
        switch ($action) {

            case 'showalbum':
                $this->headScript()
                        ->prependFile($this->basePath() . '/js/Album/index.js?version=' . $t)
                        //->prependFile($this->basePath() . '/js/Album/freewall.js?version=' . $t)
                        ->prependFile($this->basePath() . '/js/Album/main.js?version=' . $t)
                        ->prependFile($this->basePath() . '/js/Album/lazyload.js?version=' . $t)
                    ->prependFile($this->basePath() . '/js/Album/jquery.gridster.min.js?version=' . $t);
                break;
         case 'showalbumgrid':
                $this->headScript()

                        //->prependFile($this->basePath() . '/js/Album/index.js?version=' . $t)
                        ->prependFile($this->basePath() . '/js/Album/main.js?version=' . $t)
                   // ->prependFile($this->basePath() . '/js/Album/lazyload.js?version=' . $t)
                    ->prependFile($this->basePath() . '/js/Album/jquery.gridster.min.js?version=' . $t);
                break;

            default:
                break;
        }
        break;
        case 'albumdetails':
        switch ($action) {

            case 'albumpage':
                $this->headScript()
                    ->prependFile($this->basePath() . '/js/Album/index.js?version=' . $t)
                    ->prependFile($this->basePath() . '/js/Album/freewall.js?version=' . $t)
                    ->prependFile($this->basePath() . '/js/Album/main.js?version=' . $t)
                    ->prependFile($this->basePath() . '/js/Album/like.js?version=' . $t);
                break;

            default:
                break;
        }
        break;

    default:
        break;
}
echo $this->headScript()
        ->prependFile($this->basePath() . '/js/Album/tributemodal.js?version=' . $t)
        ->prependFile($this->basePath() . '/js/Album/videomodal.js?version=' . $t)
        ->prependFile($this->basePath() . '/js/Album/photomodal.js?version=' . $t)
        ->prependFile($this->basePath() . '/js/ckeditor/ckeditor.js?version=' . $t)
        ->prependFile($this->basePath() . '/js/Authorization/login.js?version=' . $t)
        ->prependFile($this->basePath() . '/js/Authorization/signup.js?version=' . $t)
        ->prependFile($this->basePath() . '/js/Album/album.js?version=' . $t)
        ->prependFile($this->basePath() . '/js/profile/tributeAdd.js?version=' . $t)
        ->prependFile($this->basePath() . '/js/profile/profile.js?version=' . $t)
        ->prependFile($this->basePath() . '/js/Album/like.js?version=' . $t)
        ->prependFile($this->basePath() . '/js/Album/resetpassword.js?version=' . $t)
        ->prependFile('//cdnjs.cloudflare.com/ajax/libs/fancybox/3.0.47/jquery.fancybox.min.js')
        //->prependFile($this->basePath() . '//code.jquery.com/jquery-3.2.1.min.js')
        ->prependFile($this->basePath() . '/js/jquery/jquery.form.js?version='.$t)
        ->prependFile($this->basePath() . '/js/bootstrap/bootstrap.min.js?version=' . $t)
        ->prependFile('//code.jquery.com/ui/1.11.3/jquery-ui.min.js')
        ->prependFile('//code.jquery.com/jquery-1.12.4.js')
        ->prependFile('//code.jquery.com/ui/1.12.1/jquery-ui.js')
        ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js')
        ->prependFile('//feather.aviary.com/js/feather.js')
        ->prependFile('//code.jquery.com/jquery-1.11.0.min.js');
?>



