
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Emmortal web site">
    <meta content="#aaa897" name="theme-color" /><meta content="width=device-width, initial-scale=1, user-scalable=no" name="viewport" />
    <meta http-equiv="cache-control" content="max-age=0" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
    <meta http-equiv="pragma" content="no-cache" />


    <title>Emmortal</title>
     <!-- <link rel="shortcut icon" type="image/x-icon" href="" />
        <link rel="apple-touch-icon" href="apple-touch-icon.png"> -->

        <!-- Place favicon.ico in the root directory -->
        <!-- Google Fonts -->
        <?php include 'albumcss.phtml'; ?>
         <?php include 'albumjs.phtml'; ?>
</head>

<body style="overflow-y: initial;">

<div class ="fullwrapnew" id="fullwrapnew" style="background-image:url('<?php echo $bgimg; ?>');background-attachment: fixed; background-repeat: no-repeat;background-size: cover;width: 100%;height:100%;min-height:500px;min-width:500px;">

    <?php  $root = $_SERVER['DOCUMENT_ROOT'];
            $root1 = explode("/public",$root);
            $path = $root1[0]."/module/Album/view/layout/navbar.phtml";
        include $path; ?>
    <?php echo $this->content; ?>
</div>
</body>
</html>
