<?php
$controller = strtolower($controller);
$action = strtolower($action);
$t = time();
switch ($controller) {
	case 'album':
		switch ($action) {   
             case 'showalbum':
$this->headLink()
                    ->prependStylesheet($this->basePath() . '/css/profile/profile.css?version=' . $t)
                    ->prependStylesheet($this->basePath() . '/css/Album/grid.css?version=' . $t)
                    ->prependStylesheet($this->basePath() . '/css/Album/jquery.gridster.min.css?version=' . $t);
                 break;
            case 'showalbumgrid':
                $this->headLink()
                    ->prependStylesheet($this->basePath() . '/css/Album/grid.css?version=' . $t)
                    ->prependStylesheet($this->basePath() . '/css/Album/jquery.gridster.min.css?version=' . $t);
                 break;
             case 'termsandconditions':
                $this->headLink()
                    ->prependStylesheet($this->basePath() . '/css/profile/profile.css?version=' . $t)
                    ->prependStylesheet($this->basePath() . '/css/profile/profilenavbar.css?version=' . $t)
                    ->prependStylesheet($this->basePath() . '/css/Album/termsconditions.css?version=' . $t)
                ;
            break;

            case 'aboutus':
                $this->headLink()
                    ->prependStylesheet($this->basePath() . '/css/profile/profile.css?version=' . $t)
                    ->prependStylesheet($this->basePath() . '/css/profile/profilenavbar.css?version=' . $t)
                    ->prependStylesheet($this->basePath() . '/css/Album/aboutus.css?version=' . $t)
                    ->prependStylesheet($this->basePath() . '/css/Album/termsconditions.css?version=' . $t)
                ;
            break;
		}
		break;
        case 'albumdetails':
		switch ($action) { 
             case 'albumpage':
                $this->headLink()
                    ->prependStylesheet($this->basePath() . '/css/profile/profile.css?version=' . $t)
                    ->prependStylesheet($this->basePath() . '/css/profile/profilenavbar.css?version=' . $t)
                    ->prependStylesheet($this->basePath() . '/css/Album/termsconditions.css?version=' . $t)
                ;
            break;
		}
		break;

	default:
		break;
}
echo $this->headLink()

        ->prependStylesheet($this->basePath() . '/css/Album/album.css?version=' . $t)

        ->prependStylesheet($this->basePath() . '/css/profile/searchfriends.css?version=' . $t)

        ->prependStylesheet($this->basePath() . '/css/profile/profilenavbar.css?version=' . $t)
        ->prependStylesheet($this->basePath() . '/css/Album/like.css?version=' . $t)
        ->prependStylesheet($this->basePath() . '/css/Album/design.css?version=' . $t)
        ->prependStylesheet($this->basePath() . '/css/Album/main.css?version=' . $t)
        ->prependStylesheet($this->basePath() . '/css/Album/style.css?version=' . $t)
        ->prependStylesheet($this->basePath() . '/css/Album/navbar.css?version=' . $t)
          ->prependStylesheet($this->basePath() . '/css/bootstrap/bootstrap.min.css?version=' . $t)
        ->prependStylesheet($this->basePath() . 'https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.0.47/jquery.fancybox.min.css')
        ->prependStylesheet($this->basePath() . 'https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css')
        ->prependStylesheet($this->basePath() . '//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css')
        ->prependStylesheet($this->basePath() . '//fonts.googleapis.com/css?family=Oxygen:400,700' );
?>
