<section class="top-bar navbar-fixed-top">
   <div class="container">
      <div class="row wrapclassrow ">
         <div>
            <div class="welcome" style="display:none;">
               <div class="close-msg">
                  <a href="#">
                  <i class="fa fa-times closebtn" aria-hidden="true"></i>
                  </a>
               </div>
               <div class="showmsg" style="margin:5px;">
                  <?php 
                     //if(strtolower($refercontroller) == 'album' && strtolower($referaction) == 'showalbum'){?>
                  <span>Welcome!</span>
                  <?php //} ?>
               </div>
            </div>
            <div class="col-lg-8" id="secondnavbarimage">
               <a href="<?php echo $dynamicPath;?>" class="logo-style">Emmortal</a>
               <?php if( $sessionid != ""){ ?>
               <!-- <button class="btn btn-default dropdown-toggle down-arrow arrow-toggle collapsed" type="button" id="dropdownMenu1" data-toggle="collapse" data-target="#dropped_ui" >
                   <i class="fa fa-chevron-up" id="arrowiconid" aria-hidden="true" style= "padding-bottom: 3px;"></i>-->
                   <!--<i class="fa fa-chevron-down" aria-hidden="true" style= "padding-bottom: 3px;"></i>-->
               <!--</button>-->
               <a class="btn btn-default dropdown-toggle down-arrow arrow-toggle collapsed" id="dropdownMenu1" href="javascript:void(0);"><div class="fa fa-chevron-up rotate"></div></a>
               <ul class="dropdown-menu profile-strip down-inner collapse sectionnavber" aria-labelledby="dropdownMenu1" id="dropped_ui">
                  <li><a class="profile-image-name-menu" href="javascript:void(0)" onclick="location.href='/profile/showprofile'"><span class="user-icon"><img src="<?php if (@getimagesize($userDetails[0]['profileimage'])) {
                    echo $userDetails[0]['profileimage'];
                } else {
                    echo "/image/profile-deafult-avatar.jpg";
                }?>"/></span><?php echo $userDetails[0]['firstname']." ".$userDetails[0]['lastname'];?></a></li>
                  <li><a href="#"  onclick="albumdetailsmodal();" class="relationships" id="<?php echo $sessionid;?>" data-name="<?php echo $userDetails[0]['firstname'];?>">Albums</a></li>
                  <li><a href="#" onclick="relationshipsmodal();" class="relationships" data-name="<?php echo $userDetails[0]['firstname'];?>">Relationships</a></li>
                  <li><a href="#">Tributes</a></li>
               </ul>
               <?php } ?>
            </div>
            <div class="col-lg-0.5">
               <ul class="nav navbar-nav hamburger-menu pull-right hoverthis">
                  <li class="dropdown hover-effect">
                     <a href="#" class="dropdown-toggle drop-list-icon" data-toggle="dropdown"><span class="glyphicon glyphicon-user menu-icon pull-right"><i class="fa fa-bars" aria-hidden="true"></i></span></a>
                     <ul class="dropdown-menu topbar-dropdown drop-border drop-bg">
                        <li><?php if($sessionid == ""){ ?><button onclick="squarespaceModalopen();" class="btn btn-primary center-block sign-up">Sign Up</button><?php }?>
                        </li>
                        <li><?php if($sessionid == ""){ ?><button onclick="squarespaceModal2open();"  class="btn btn-primary center-block sign-up">Sign In</button><?php }?>
                        </li>
                        <li><?php if($sessionid != ""){ ?><button class="btn btn-primary center-block sign-up" onclick="location.href='/profile/showprofile'">My profile</button><?php }?>
                        </li>
                        <li><?php if($sessionid != ""){ ?>
                           <button class="btn btn-primary center-block sign-up" onclick="location.href='/profile/newsfeed'">Newsfeed</button><?php }?>
                        </li>
                        <?php if($sessionid != ""){ ?>
                        <li><button class="btn btn-primary center-block sign-up" onclick="location.href='/settings/general'">Settings</button>
                        </li>
                        <?php }?>
                        <li><button class="btn btn-primary center-block sign-up" onclick="location.href='/album/aboutus'">About Us</button></li>
                        <li><button class="btn btn-primary center-block sign-up" onclick="location.href='/album/termsandconditions'">Terms & Conditions</button></li>
                        <li>
                           <?php if( $sessionid != ""){ ?>
                           <form class="form-horizontal style-form" id='userLogout' method="post"   action="/profile/logoutuser" enctype="multipart/form-data"><button class="btn btn-primary center-block sign-up" >Logout</button></form>
                           <?php }?><!--onclick="location.href='/album/showalbum'"-->
                        </li>
                     </ul>
                  </li>
               </ul>
            </div>
            <?php if ($sessionid != ""){ ?>
            <div class="col-lg-0.5">
               <ul class="nav navbar-nav hamburger-menu pull-right hoverthis">
                  <li class="dropdown hover-effect">
                     <a href="javascript:void(0);" class="dropdown-toggle drop-list-icon" onclick="uploadmodalopen();"><span class="glyphicon glyphicon-user menu-icon pull-right"><i class="fa fa-plus" aria-hidden="true"></i></span></a>
                  </li>
               </ul>
            </div>
            <div class="col-lg-0.5">
               <ul class="nav navbar-nav hamburger-menu pull-right hoverthis">
                  <li class="dropdown hover-effect">
                     <a href="javascript:void(0);" class="dropdown-toggle drop-list-icon" onclick="searchmodalopen();"  id="searchfriend"><span class="glyphicon glyphicon-user menu-icon pull-right"><i class="fa fa-search" aria-hidden="true"></i></span></a>
                  </li>
               </ul>
            </div>
            <div class="col-lg-0.5">
               <ul class="nav navbar-nav hamburger-menu pull-right hoverthis">
                  <li class="dropdown hover-effect">
                     <a href="javascript:void(0);" class="dropdown-toggle drop-list-icon getTribute" data-id="" data-cmd="">
                     <span class="glyphicon glyphicon-user menu-icon pull-right">
                     <i class="fa fa-comments" aria-hidden="true"></i>
                     </span>
                     </a>
                     
                  </li>
               </ul>
            </div>
            <div class="col-lg-0.5">
               <ul class="nav navbar-nav hamburger-menu pull-right hoverthis">
                  <li class="dropdown hover-effect e-dropdown dropdown notifications-dropdown white-dropdown">
                      <a href="javascript:void(0);" class="dropdown-toggle drop-list-icon notification-click"><span class="glyphicon glyphicon-user menu-icon pull-right bellblush"><i class="fa fa-bell" aria-hidden="true"></i><span class="countable m-r-5" id="noticnt"></span></span></a>
                     <!-- Notification Start -->
                      <div id="notification-div" style="display:none;"></div>
                    <!-- Notification End -->

                  </li>
               </ul>
            </div>
            <?php }?>
         </div>
      </div>
   </div>
    <?php if(($controller == 'profile') && ($action == 'newsfeed') && ($tempsessionid != 'blank')) {?>
       <input type="hidden" value="<?php echo $tempsessionid;?>"> 
    <?php }?>
    <div id="welcome" style="display: none;" class="welcome">
        <div class="close-msg">
          <a href="#">
          <i aria-hidden="true" class="fa fa-times closebtn"></i>
          </a>
        </div>
        <div id="showmsg" style="margin:5px;" class="showmsg"></div>
    </div>
</section>

<?php //include_once($_SERVER['DOCUMENT_ROOT']."/modal/signupmodal.php"); ?>
<?php //include_once($_SERVER['DOCUMENT_ROOT']."/modal/loginmodal.php"); ?>
<?php //include_once($_SERVER['DOCUMENT_ROOT']."/modal/forgetpasswordmodal.php"); ?>
<?php //include_once($_SERVER['DOCUMENT_ROOT']."/modal/uploadmodal.php"); ?>
<?php //include_once($_SERVER['DOCUMENT_ROOT']."/modal/textinsertmodal.php"); ?>
<?php //include_once($_SERVER['DOCUMENT_ROOT']."/modal/imageinsertmodal.php"); ?>
<?php //include_once($_SERVER['DOCUMENT_ROOT']."/modal/videoinsertmodal.php"); ?>
<?php //include_once($_SERVER['DOCUMENT_ROOT']."/modal/tributemodal.php"); ?>
<?php //include_once($_SERVER['DOCUMENT_ROOT']."/modal/searchmodal.php"); ?>
<?php //include_once($_SERVER['DOCUMENT_ROOT']."/modal/textpreviewmodal.php"); ?>
<?php //include_once($_SERVER['DOCUMENT_ROOT']."/modal/imagepreviewmodal.php"); ?>
<?php //include_once($_SERVER['DOCUMENT_ROOT']."/modal/showimagepreviewmodal.php"); ?>
<?php //include_once($_SERVER['DOCUMENT_ROOT']."/modal/videopreviewmodal.php"); ?>
<?php //include_once($_SERVER['DOCUMENT_ROOT']."/modal/tributeaddmodal.php"); ?>
<?php //include_once($_SERVER['DOCUMENT_ROOT']."/modal/friendtributeaddmodal.php"); ?>



