
<div class="main_section" style="margin-top:80px !important;">
<!--    <div class=col-md-12>-->
<!--
        <div class=col-md-2></div>
        <div class=col-md-8>
-->
			<h3 class="termsHeader" id="aboutUsAlb">About Us</h3>
<!--
        </div>
        <div class=col-md-2></div>
-->
<!--    </div>-->
            <!-- content goes here -->
<!--    <div class=col-md-12>-->
<!--
        <div class=col-md-2></div>
        <div class=col-md-8>
-->
		    <div class="termsBody">
                <p class="moodal-text inner_content">Your family photo album for the interactive age, Emmortal.com is your opportunity to decide how you want your lifetime of experiences, passions, and celebrations to be remembered for future generations.</p>
		    </div>
<!--
        </div>
        <div class=col-md-2></div>
-->
<!--    </div>-->
</div><!--/main_section-->
