<!--main section-->
<div class="main_section" style="margin-top:80px !important;">

			<h3 class="termsHeader" id="aboutUsAlb">About Us</h3>

		    <div class="termsBody">
                <p class="moodal-text inner_content">Your family photo album for the interactive age, Emmortal.com is your opportunity to decide how you want your lifetime of experiences, passions, and celebrations to be remembered for future generations.</p>
		    </div>

</div>
<!--/main_section-->
