<section class="photo-collage"><!--style="background: <?php //echo $bgimg[0]['bgimage'];?> !important;"-->
   <div class="container">
      <div class="row">
         <div class="layout">
       
<input type="hidden" id="isAjaxStart" value=0 />
<input type="hidden" id="checker" value=1 />
<input type="hidden" id="counterOfTheTemplate" value=0 />
           <div class="gridster ready">
                           


 
                  <?php  
                   $u = count($uploadDetails);
                   if($u>0){?>
                        <input type='hidden' id ='noOfTemplates' value="<?php echo $u; ?>" >
                <input type ="hidden" value="1" id="valuetobeIncremented">
                                       <?php 
                                       if ($u < 15) {
                        $no = $u;
                    } else {
                        $no = 15;
                    } ?>
                      <ul id="outer-wrap">
                       <?php for ($i = 0; $i < $no; $i++) {
                       // for($j = 0;$j< count($likeDetailsArrays); $j++){
                           $uploadId = $uploadDetails[$i]['uploadId'];

                                         if($uploadDetails[$i]['uploadType'] == "text"){

                                             echo ' <li class="gs-w previewUploadedFile" data-sizey="'.$uploadDetails[$i]['sizeY'].'" data-sizex="'.$uploadDetails[$i]['sizeX'].'" data-col="1" data-row="1" data-cmd="text" data-id="'.$uploadDetails[$i]['uploadId'].'">
                                             <span><label name="text Name"><p>'.$uploadDetails[$i]['uploadTitle'].'</p><p>'.$uploadDetails[$i]['uploadDescription'].'</p></label></span><div class="inner-box"> '.$likeDetailsArrays[0][$uploadId].' </div>


               </li>';
                                          }

                                          else if($uploadDetails[$i]['uploadType'] == "image"){
                                              if (@getimagesize($uploadDetails[$i]['uploadPath'])) {
                                                  $uploadedImage = $uploadDetails[$i]['uploadPath'];
                                              }else{
                                                  $uploadedImage = $dynamicPath."/image/NoPhotoDefault.png";
                                              }

                                              echo ' <li class="gs-w previewUploadedFile" data-sizey="'.$uploadDetails[$i]['sizeY'].'" data-sizex="'.$uploadDetails[$i]['sizeX'].'" data-col="1" data-row="1" data-cmd="image" data-id="'.$uploadDetails[$i]['uploadId'].'">
                                              <span><img name="ImageName" id="" src="'.$uploadedImage.'" style="width:100%;height:100%;"></span><div class="inner-box"> '.$likeDetailsArrays[0][$uploadId].' </div>


               </li>';

                                          }
                                           else if($uploadDetails[$i]['uploadType'] == "video"){

                                                echo ' <li class="gs-w previewUploadedFile" data-sizey="'.$uploadDetails[$i]['sizeY'].'" data-sizex="'.$uploadDetails[$i]['sizeX'].'" data-col="1" data-row="1" data-cmd="video" data-id="'.$uploadDetails[$i]['uploadId'].'">
                                                <span><video controls="controls" name="Video Name" id="" src="'.$uploadDetails[$i]['uploadPath'].'" style="width:100%;height:100%;"></video></span><div class="inner-box"> '.$likeDetailsArrays[0][$uploadId].' </div>


               </li>';


                                           }
                                           else{

                                           }
                                        }
                                      //}
                                     }?>

          
                </ul>
                  <div id='loader-icon' style="display: none;">
    <img src='<?php echo $dynamicPath; ?>/image/load3.gif' alt="loader" />
    <p>Loading more widgets...</p>
</div>
            </div>
        
         </div>

         </div>
         
                 

      </div>
<ul class="clickme" style="display:none"></ul>
</section>
<!-- line modal -->

<!-- line modal 2-->

<!-- modal for forget email -->

<!-- line modal 3-->

<!-- line modal 4-->
