<?php //echo "jksgdfrdhgtlgrtuhthtyhjty dsgdfhfh "; ?>
<section class="photo-collage"><!--style="background: <?php //echo $bgimg[0]['bgimage'];?> !important;"-->
   <div class="container">
      <div class="row">
         <div class="layout">
            <div id='loader-icon' style="display: none;">
    <img src='<?php echo $dynamicPath; ?>/image/load3.gif' alt="loader" />
</div>
<input type="hidden" id="isAjaxStart" value=0 />
<input type="hidden" id="checker" value=1 />
<input type="hidden" id="counterOfTheTemplate" value=0 />
            <div class="content-wrapper user_profile_section">
               <div class="container-of-sections ">
                           


 
                  <?php  
                   $u = count($uploadDetails);
                   if($u>0){?>
                        <input type='hidden' id ='noOfTemplates' value="<?php echo $u; ?>" >
                <input type ="hidden" value="1" id="valuetobeIncremented">
                                       <?php 
                                       if ($u < 15) {
                        $no = $u;
                    } else {
                        $no = 15;
                    } ?>
                      <ul class="outer-wrap" id="outer-wrap">
                        <?php for ($i = 0; $i < $no; $i++) {
                           $uploadId = $uploadDetails[$i]['uploadId'];


                                          if($uploadDetails[$i]['uploadType'] == "text"){
                                             echo ' <li class="user_upload_part_section_content--inside vid-sec text-sec previewUploadedFile" style="height:220px;width:20%;" data-cmd="text" data-id="'.$uploadId.'" data-toggle="modal">
                  <span><label name="text Name">'.$uploadDetails[$i]['uploadTitle'].'<p>'.$uploadDetails[$i]['uploadDescription'].'</p></label></span><div class="inner-box"> 0 </div>
               </li>';
                                          }

                                          else if($uploadDetails[$i]['uploadType'] == "image"){
                                              echo ' <li class="user_upload_part_section_content--inside vid-sec previewUploadedFile" style="height:220px;width:20%;" data-cmd="image" data-id="'.$uploadId.'" data-toggle="modal">
                  <span><img name="Image Name" id="" src="'.$uploadDetails[$i]['uploadPath'].'" style="width:100%;height:100%;"></span><div class="inner-box"> 0 </div>
               </li>';

                                          }
                                           else if($uploadDetails[$i]['uploadType'] == "video"){
                                                echo ' <li class="user_upload_part_section_content--inside vid-sec previewUploadedFile" style="height:220px;width:20%;" data-cmd="video" data-id="'.$uploadId.'" data-toggle="modal">
                  <span><video controls="controls" name="Video Name" id="" src="'.$uploadDetails[$i]['uploadPath'].'" style="width:100%;height:100%;"></video></span><div class="inner-box"> 0 </div>
               </li>';


                                           }
                                           else{

                                           }
                                        }
                                     }?>

          
                </ul>
            </div>
        
         </div>
         </div>
      </div>
   </div>
</section>
<!-- line modal -->

<!-- line modal 2-->

<!-- modal for forget email -->

<!-- line modal 3-->

<!-- line modal 4-->
