<?php //echo "jksgdfrdhgtlgrtuhthtyhjty dsgdfhfh "; ?>
    <section class="photo-collage">
        <div class="container">
            <div class="row">
    
                <div class="layout">

                    <div class="free-wall">
                        <div class="size320" data-nested=".level-1" data-gutterX=10 data-gutterY=10 data-cellW=0.5 data-cellH=0.5 >
                            <div class="brick level-1 size24"></div>
                            <div class="brick level-1 size24"></div>
                        </div>
                        <div class="size320" data-nested=".level-1"  data-gutterX=10 data-gutterY=10 data-cellW=0.5 data-cellH=0.5 >
                            <div class="brick level-1 size42"></div>
                            <div class="brick level-1 size42"></div>
                        </div>
                        <div class="size320" data-nested=".level-1"  data-gutterX=10 data-gutterY=10 data-cellW=0.5 data-cellH=0.5 >
                            <div class="brick level-1 size108"></div>
                            <div class="brick level-1 size108"></div>
                        </div>
                        <div class="size320" data-nested=".level-1"  data-gutterX=10 data-gutterY=10 data-cellW=0.5 data-cellH=0.5 >
                            <div class="brick level-1 size24"></div>
                            <div class="brick level-1 size22"></div>
                            <div class="brick level-1 size22"></div>
                        </div>
                        <div class="size320" data-nested=".level-1" data-gutterX=10 data-gutterY=10 data-cellW=0.5 data-cellH=0.5 >
                            <div class="brick level-1 size42"></div>
                            <div class="brick level-1 size22"></div>
                            <div class="brick level-1 size22"></div>
                        </div>
                        <div class="size320" data-nested=".level-1"  data-gutterX=10 data-gutterY=10 data-cellW=0.5 data-cellH=0.5 >
                            <div class="brick level-1 size22"></div>
                            <div class="brick level-1 size24"></div>
                            <div class="brick level-1 size22"></div>
                        </div>
                        <div class="size320" data-nested=".level-1"  data-gutterX=10 data-gutterY=10 data-cellW=0.5 data-cellH=0.5 >
                            <div class="brick level-1 size22"></div>
                            <div class="brick level-1 size22"></div>
                            <div class="brick level-1 size22"></div>
                            <div class="brick level-1 size22"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    



<!-- line modal -->
<div class="modal fade" id="squarespaceModal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog modal-box signup_popup">
  <div class="modal-content modal-outer">
    <div class="modal-header modal-headernew">
      <button type="button" class="close close-new" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
      <h3 class="modal-title" id="lineModalLabel">Create a Profile and Become Emmortal</h3>
    </div>
    <div class="modal-body">
      
            <!-- content goes here -->
      <form method="post" action="/authsignup/signup" enctype="multipart/form-data" name="nameform" id="signup_form">
              <div class="form-group input-box">
                <input type="text" class="form-control" id="fname" placeholder="First Name">
              </div>
              <div class="form-group input-box">
                <input type="text" class="form-control" id="lname" placeholder="Last Name">
              </div>
              <div class="form-group  full-width">
                <input type="text" class="form-control" id="email" placeholder="Email">
              </div>
                <div class="form-group full-width">
                <input type="password" class="form-control" id="password" placeholder="Password">
              </div>
                <div class="form-group full-width">
                <input type="password" class="form-control" id="confirmPassword" placeholder="Confirm Password">
              </div>
              <div class="form-group full-width date-picker" id='datetimepicker2'>
                <input type="text" class="form-control " id="datepicker" placeholder="Date of Birthday">
              </div>
               <button type="submit" value="Submit" style="display:none;">Sign Up</button>
            </form>
            <div class="modal-footersec">
                <p>By clicking Sign Up, you agree to our <a href="#" class="link-color">Terms and conditions</a></p>
               
                 <a class="modal-button" id="signupbutton">Sign Up</a> 
                 <div class="alertmesage_signup" style="display: none;"></div>
                <p>Already have an account? Please, <a id="signin" class="link-color" data-toggle="modal" data-target="#squarespaceModal2">Sign In</a></p>  
            </div>
    </div>
  </div>
  </div>
</div>
    
    <!-- line modal 2-->
<div class="modal fade" id="squarespaceModal2" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog modal-box signin_popup">
  <div class="modal-content modal-outer">
    <div class="modal-header modal-headernew">
      <button type="button" class="close close-new" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
      <h3 class="modal-title" id="lineModalLabel">Sign In</h3>
    </div>
    <div class="modal-body">
      
            <!-- content goes here -->
      <form method="post" action="/authlogin/login" enctype="multipart/form-data" name="nameform" id="login_form">
              <div class="form-group  full-width">
                <input type="text" class="form-control" id="loginemail" placeholder="Email">
              </div>
                <div class="form-group full-width">
                <input type="password" class="form-control" id="loginpassword" placeholder="Password">
              </div>
                <a data-toggle="modal" data-target="#squarespaceModalemail" class="link-color use-margin" id="forgotmail" onclick="showhide();">Forgot Password?</a>
                <button type="submit" value="Submit" style="display:none;"></button>
      </form>
            <div class="modal-footersec">
                <div class="button-div">
                  <a class="modal-button" id="signinbutton">Sign IN</a> 
                  <div class="alertmesage_signin" style="display: none;"></div>
                </div>
                <p>Don't have an account? Please,  <a id="signup" class="link-color" data-toggle="modal" data-target="#squarespaceModal">Sign Up</a></p>
            </div>
    </div>
  </div>
  </div>
</div>
<!-- modal for forget email -->
<div class="modal fade" id="squarespaceModalemail" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog modal-box signin_popup">
  <div class="modal-content modal-outer">
    <div class="modal-header modal-headernew">
      <button type="button" class="close close-new" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
      <h3 class="modal-title" id="lineModalLabel">Recovery password</h3>
    </div>
    <div class="modal-body">
      
            <!-- content goes here -->
      <form method="post" action="/authlogin/recover" enctype="multipart/form-data" name="nameform" id="recovery_form">
              <div class="form-group  full-width">
                <input type="text" class="form-control" id="recoveryemail" placeholder="Email">
              </div>
                <a id="back" data-toggle="modal" data-target="#squarespaceModal2" class="link-color use-margin" onclick="showhide();">Back</a>
                <button type="submit" value="Submit" style="display:none;"></button>
      </form>
            <div class="modal-footersec">
                <div class="button-div">
                  <a class="modal-button" id="recoverybutton">Recovery</a> 
                  <div class="alertmesage_recovery" style="display: none;"></div>
                </div>
            </div>
    </div>
  </div>
  </div>
</div>


    
     <!-- line modal 3-->
<div class="modal fade" id="squarespaceModal3" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog modal-box">
    <div class="modal-content modal-outer">
        <div class="modal-header modal-headernew">
            <button type="button" class="close close-new" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
            <h3 class="modal-title" id="lineModalLabel">About Us</h3>
        </div>
        <div class="modal-body">
            
            <!-- content goes here -->
            <p class="moodal-text">Your family photo album for the interactive age, Emmortal.com is your opportunity to decide how you want your lifetime of experiences, passions, and celebrations to be remembered for future generations.</p>
        </div>
        <div class="modal-footer close-area">
            <div class="btn-group btn-group-justified button-style" role="group" aria-label="group button">
                <div class="btn-group cancel-button" role="group">
                    <button type="button" class="btn btn-default main-button" data-dismiss="modal"  role="button">Close</button>
                </div>
                <div class="btn-group btn-delete hidden" role="group">
                    <button type="button" id="delImage" class="btn btn-default btn-hover-red" data-dismiss="modal"  role="button">Delete</button>
                </div>
            </div>
        </div>
    </div>
  </div>
</div>
    
    
<!-- line modal 4-->
<div class="modal fade" id="squarespaceModal4" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog modal-box">
    <div class="modal-content modal-outer">
        <div class="modal-header modal-headernew">
            <button type="button" class="close close-new" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
            <h3 class="modal-title" id="lineModalLabel">EMMORTAL TERMS AND CONDITIONS</h3>
        </div>
        <div class="modal-body terms-body">
            
            <!-- content goes here -->
            <div class="moodal-text terms-c">
                <h4>OVERVIEW</h4>
                <p>This website, technology, and the services provided through this website and associated technology are owned and operated by Emmortal, LLC (hereinafter “Emmortal”). Emmortal offers its services, including all information, tools, features, technology and services available from this website to you, the user, conditioned upon your acceptance of all terms, conditions, policies and notices stated here.</p>
                <p>By visiting the Emmortal website and/ or purchasing any services or products and/or using any information, features, tools, and technology from Emmortal (individually and collectively the “Services”), you agree to be bound by the following terms and conditions (“Terms and Conditions” or “Terms”), including those additional terms and conditions and policies referenced herein and/or available by hyperlink. These Terms and Conditions apply to all users of this website and the Services, including, without limitation, users who are browsers, vendors, customers, merchants, and/ or contributors of content.</p>
                <p>Please read these Terms and Conditions carefully before accessing or using the Emmortal website or the Services. By accessing or using any part of the Emmortal website or the Services, you agree to be bound by these Terms and Conditions. If you do not agree to all the terms and conditions of this agreement, then you may not access the website or use any Services. If these Terms and Conditions are considered an offer, acceptance is expressly limited to these Terms and Conditions.</p>
                <p>Any new features, tools, and/or services and/or substantive change to existing features, tools, and/or services which are added and/or made to the Emmortal website shall also be subject to these Terms and Conditions. You can review the most current version of the Terms and Conditions at any time on the Emmortal website. Emmortal reserves the right to update, change or replace any part of these Terms and Conditions by posting updates and/or changes to the Emmortal website. It is your responsibility to check this page periodically for changes. Your continued use of or access to the Emmortal website and the Services following the posting of any changes constitutes acceptance of those changes.</p>
                <p>The headings used in this agreement are included for convenience only and will not limit or otherwise affect these Terms.</p>
                <h4>SECTION 1 – USER’S USE OF SERVICES TERMS</h4>
                <p>By agreeing to these Terms and Conditions, you represent that you are at least the age of majority in your state, province, or country of residence, or that you are the age of majority in your state, province, or country of residence and you have given Emmortal your consent to allow any of your minor dependents to use the Emmortal website and access the Services.</p>
                <p>You may not use the Services for any illegal or unauthorized purpose nor may you, in the use of the Services, violate any laws in your jurisdiction (including but not limited to copyright laws).</p>
                <p>You are not permitted to transmit any worms or viruses or any code of a destructive nature.</p>
                <p>A breach or violation of any of the Terms may result in the immediate termination of the Services.</p>
                <p>You are responsible for the security of your own account with Emmortal including your password and account credentials. You are required to notify Emmortal if your account is in anyway compromised including, but not limited to having lost, stolen, or otherwise provided unauthorized access to third parties. You are solely responsible for any activity that occurs under your account and are responsible for any loss or misuse of your content or breach of ownership or intellectual property rights by any third party if you fail to maintain the security of your password and credentials.</p>
                <h4>SECTION 1 – USER’S USE OF SERVICES TERMS</h4>
                <h4>SECTION 2 - GENERAL CONDITIONS</h4>
                <p>Emmortal reserves the right to refuse service to anyone for any reason at any time.</p>
                <p>You understand that your content (not including credit card information), may be transferred unencrypted and involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices.</p>
                <p>You agree not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Services without the prior, express written permission by Emmortal.</p>
            </div>
        </div>
        <div class="modal-footer close-area">
            <div class="btn-group btn-group-justified button-style" role="group" aria-label="group button">
                <div class="btn-group cancel-button" role="group">
                    <button type="button" class="btn btn-default main-button" data-dismiss="modal"  role="button">Close</button>
                </div>
                <div class="btn-group btn-delete hidden" role="group">
                    <button type="button" id="delImage" class="btn btn-default btn-hover-red" data-dismiss="modal"  role="button">Delete</button>
                </div>
            </div>
        </div>
    </div>
  </div>
</div>