<section id="main-content">
	<section class="wrapper">
		<h3>
			<i class="fa fa-angle-right"></i>Background Image Edit
		</h3>
		<!-- BASIC FORM ELELEMNTS -->
		<div class="row mt">
			<div class="col-lg-12">

        <!-- add user layout -->
				<div class="container">
                    <form class="form-login reg-form" id='bgimgEditForm' method="post" action="/seomanage/bgeditsubmit" enctype="multipart/form-data">
                    <h2 class="form-login-heading">Edit Background Image</h2>
                        <div class="reg-wrap">
                            <input type="hidden" id="bgimgid" name="bgimgid" value="<?php echo $bgimg[0]['bgimgid']; ?>">
								<div id="upload_prev" class="upload_prev" style="margin-left: 12em; padding-bottom: 10px;">
									<?php if(!empty($bgimg[0]['bgimgpath'])){ ?>
									<img class="image" src="<?php echo $bgimg[0]['bgimgpath'] ?>" onerror="this.src='/image/profile-deafult-avatar.jpg'" height="100px" width="100px" style="margin: 5px 12em 0 0;" />
									<?php } else{ ?><img class="image" src="<?php echo $bgimg[0]['bgimgpath'] ?>" onerror="this.src='/image/profile-deafult-avatar.jpg'" height="100px" width="100px" style="margin: 5px 12em 0 0;" />
                                    <?php }?>

								</div>
                                <label id="errorImg1" style="margin-left: 10px;"></label><!--img extnsn valid-->
								<label id="errorImg2" style="margin-left: 70px;"></label><!--img size(>1MB) valid-->
                                <input type="file" class="form-control" name="fileupload" id="fileupload" style='height: 30%;' required />

                            <br>
                            <input type="button" class="btn btn-theme btn-block" id="bgImgSave" value="Save and Continue">
                        </div>
                    </form>
                </div>
                <!-- /add user layout -->

			</div>
			<!-- /col-lg-12 -->
	</div>
		<!-- /row -->
	</section>
	<!--/wrapper -->
</section>
<!-- /MAIN CONTENT -->
