<section id="main-content">
	<section class="wrapper">
		<h3>
			<i class="fa fa-angle-right"></i>Background Image Edit
		</h3>
		<!-- BASIC FORM ELELEMNTS -->
		<div class="row mt">
			<div class="col-lg-12">

        <!-- add user layout -->
				<div class="container">
                    <form class="form-login reg-form" id='bgimgEditForm' method="post" action="/seomanage/bgimgupdate" enctype="multipart/form-data">
                    <h2 class="form-login-heading">Edit Background Image</h2>
                        <div class="reg-wrap col-md-12">
                            <input type="hidden" id="bgimgid" name="bgimgid" value="<?php echo $bgimg[0]['bgimgid']; ?>" />
                            <input type="hidden" id="imgSrc" name="imgSrc" />
								<div id="upload_prev" class="upload_prev col-md-6" style="padding-bottom: 20px; padding-left: 50px;">
									<?php if(!empty($bgimg[0]['bgimgpath'])){ ?>
									<img class="image" id="image" src="<?php echo $bgimg[0]['bgimgpath'] ?>" onerror="this.src='/image/profile-deafult-avatar.jpg'" height="100px" width="100px" style="margin: 5px 12em 0 0;" />
									<?php } else{ ?><img class="image" src="<?php echo $bgimg[0]['bgimgpath'] ?>" onerror="this.src='/image/profile-deafult-avatar.jpg'" height="100px" width="100px" style="margin: 5px 12em 0 0;" />
                                    <?php }?>

								</div>
                                <div class="col-md-6">
                                    <button type="button" class="btn btn-primary btn-lg modBtn" id="modBtn" data-toggle="modal" data-target="#myModal">Choose Image</button>
                                </div>

                            <br>
                            <input type="button" class="btn btn-theme btn-block bgImgSave" id="bgImgSave" value="Save and Continue">
                        </div>
                    </form>
                </div>
                <!-- /add user layout -->

			</div>
			<!-- /col-lg-12 -->
	</div>
		<!-- /row -->
	</section>
	<!--/wrapper -->
</section>
<!-- /MAIN CONTENT -->

   <!--modal (start)-->
    <!-- Modal -->
<div class="modal fade" id="myModal"  role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>

                </button>
                 <h4 class="modal-title" id="myModalLabel">Choose Image</h4>

            </div>
            <div class="modal-body">
                <div role="tabpanel">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active" id="upload"><a href="#uploadTab" aria-controls="uploadTab" role="tab" data-toggle="tab">MY IMAGES</a>

                        </li>
                        <li role="presentation" id="browse"><a href="#browseTab" aria-controls="browseTab" role="tab" data-toggle="tab">PATTERNS</a>

                        </li>
                    </ul>
                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane active uploadTab" id="uploadTab">
                          <div class="col-md-12">
<!--                            <div class="col-sm-12">-->
                                <div class="col-md-6">
                                    <label class="uploadbtn">Upload Image</label>
                                    <form class="form-login reg-form" id='imgUploadForm' name="imgUploadForm" method="post" action="/seomanage/bgeditsubmit" enctype="multipart/form-data">
                                        <input type="file" class="form-control uploadbtn-input-file" name="fileupload" id="fileupload" style='height: 30%;' required />
                                     </form>
                                </div>
                                <div id="img_prev" class="img_prev col-md-6" style="padding-left: 60px;">
									<img class="imgPrev" id="imgPrev" src="" onerror="this.src='/image/profile-deafult-avatar.jpg'" height="100px" width="100px" style="margin-top: 5px;" />
                                 </div>
                                    <label id="errorImg1" class="col-md-6" style="top: 15px;"></label><!--img extnsn valid-->
<!--                                    style="margin-left: 10px;"-->
                                    <label id="errorImg2" class="col-md-6" style="top: 15px;"></label><!--img size(>1MB) valid-->
                                    <!-- style="margin-left: 70px;"-->

<!--

                                </div>
-->
                              <div class="col-sm-12" class="savedImg" id="savedImg" style="margin: 10px 0 0px -45px;"></div>
                            </div><!--/col-md-12-->

                            <div class="col-sm-4"></div>
                          </div><!-- /col-md-12 -->
                        </div><!-- /uploadTab -->

                        <div role="tabpanel" class="tab-pane col-sm-12 browseTab" id="browseTab">
                        <div class="imgAppend" id="imgAppend"></div>
                        </div>
                   </div>
                </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary save" data-dismiss="modal">Save changes</button>
            </div>
        </div>
    </div>
</div>
   <!--modal (end)-->


