<!--main content start-->
<section id="main-content">
	<section class="wrapper">
		<h3>
			<i class="fa fa-angle-right"></i>Edit SEO Details
		</h3>

		<!-- BASIC FORM ELELEMNTS -->
		<div class="row mt">
			<div class="col-lg-12">
				<div class="form-panel">
					<form class="form-horizontal style-form" id='seoFormEdit'
						method="post"
						action="/seomanage/editseosubmit"
						 enctype="multipart/form-data">

						 <?php if(!empty($seodata)){
								foreach($seodata as $key => $val)
					               { ?>
					    <input type="hidden" name="seoId" id="seoId" value="<?php echo $val['seoid'];?>">
                        <div class="form-group">
							<label class="col-sm-4 control-label">Page title :</label>
							<div class="col-md-6">
								<input type="text" class="form-control" id="seoTitle"
									name='seoTitle' value="<?php echo strip_tags($val['seopagetitle']);?>" />
								<span class="help-block" style="display:none;" id="errorTitle"></span>
							</div>
						</div>
                        <div class="form-group">
							<label class="col-sm-4 control-label">Meta description :</label>
							<div class="col-md-6">
								<textarea type="text" class="form-control" id="metaDesc"
									name='metaDesc'><?php echo strip_tags($val['seometadescription']);?></textarea>
								<span class="help-block" style="display:none;" id="errorDesc"></span>
							</div>
						</div>
						<div class="form-group">
							<label class="col-sm-4 control-label">Image path :</label>
							<div class="col-md-6">
								<input type="text" class="form-control" id="imgPath"
									name='imgPath' value="<?php echo $val['seoOGimagepath'];?>" />
                                <span class="help-block" style="display:none;" id="errorImg"></span>
							</div>
						</div>
                        <div class="form-group">
							<label class="col-sm-4 control-label">Favicon path:</label>
							<div class="col-md-6">
								<input type="text" class="form-control" id="favicon"
									name='favicon' value="<?php echo $val['seoFaviconimagepath'];?>" />
                                <span class="help-block" style="display:none;" id="errorIcon"></span>
							</div>
						</div>

						<div class="btndiv_cls">
                            <button class="btn_cls" type="button" id='btnSave' value="Save and Continue">Save and Continue</button>
						</div>

                    <?php }
                            }
							else
							{
							   echo "No records found...";
							}?>
					</form>
				</div>
				<!-- /form-panel -->
			</div>
			<!-- /col-lg-12 -->


		</div>
		<!-- /row -->
	</section>
	<!--wrapper -->

</section>
<!-- /MAIN CONTENT -->
