
<section id="main-content">
	<section class="wrapper">
		<h3 style="text-align:center;">
			Emmortal SEO Details
		</h3>
		<div class="col-sm-12"
			style="margin-bottom: 20px; padding: 0 !important">

            <h1 id="csv_title" style="display: none;">Emmortal Seo Details</h1>
            <a href="/seomanage/bgedit" class="new_user" title="Change Background Image">Background Image</a>
		</div>

		<div class="row mt">
			<div class="col-md-12">
				<div class="content-panel" style="padding-top: 5px;">


                        <table class="table table-striped table-advance table-hover tbody userDetails datatable sortable" name="userDetails" id="userDetails">

						<thead>
							<tr class="show_rows">
								<td style="cursor: pointer; font-weight: bold;" class="hidden-phone"><i
									class="fa fa-bookmark"></i> Title</td>
								<td style="cursor: pointer; font-weight: bold;" class="hidden-phone"><i
									class="fa fa-bookmark"></i> Description</td>
                                <td style="cursor: pointer; font-weight: bold;" class="hidden-phone"><i
									class="fa fa-bookmark"></i> Seo image</td>
                                <td style="cursor: pointer; font-weight: bold;"><i
									class="fa fa-bookmark"></i> Favicon</td>
								<td style="cursor: pointer; font-weight: bold;"><i
									class="fa fa-bookmark"></i> Creation date</td>
                                <td style="cursor: pointer; font-weight: bold;" class="sorttable_nosort"><i
									class="fa fa-bookmark"></i> Action</td>
							</tr>
						</thead>

						<tbody class="my_size">
							<?php if(!empty($seodata)){
								foreach($seodata as $key => $val)
					               { ?>

							<tr	class="manageAll catId show_rows">
								<td class="hidden-phone"><?php if(!empty($val['seopagetitle'])){
                                    echo strip_tags($val['seopagetitle']);} else{ echo "N/A"; }
                                    ?></td>
								<td class="hidden-phone email-width"><span class=""
									style=""><?php echo strtolower($val['seometadescription']); ?>
								</span></td>
                                <td class="hidden-phone profileImg"><span class="profileImg"
									style="padding: 5px; font-weight: bold;"><img src="<?php echo $val['seoOGimagepath'];?>"  height="100px" width="100px" />
								</span></td>
                                <td class="hidden-phone profileImg"><span class="profileImg"
									style="padding: 5px; font-weight: bold;"><img src="<?php echo $val['seoFaviconimagepath'];?>"  height="100px" width="100px" />
								</span></td>
                                <td class="hidden-phone"><?php echo $val['creationDate'];?></td>
                                <input type="hidden"  class="hidden_class" value="<?php echo $val['seoid']; ?>" />
								<td class="sorttable_nosort">

                                    <a href="<?php echo '/seomanage/editseo/'.$val['seoid']; ?>" title="Edit SEO details">
                                            <button class="btn btn-primary btn-xs edit_seo">
                                                <i class="fa fa-pencil" aria-hidden="true"></i>
                                            </button>
                                    </a>

								</td>
							</tr>
							<tr id="hidden_tr" style="display: none;" class="for_search">
								<th style="border-bottom: 0px !important;">No records found</th>
							</tr>
							<?php }
                            }
							else
							{
							   echo "No records found...";
							}?>
						</tbody>
					</table>
				</div>
				<!-- /content-panel -->

			</div>
			<!-- /col-md-12 -->
		</div>
		<!-- /row -->

	</section>
	<!-- /wrapper -->

</section>
<!-- /MAIN CONTENT -->

