
<section id="main-content">
	<section class="wrapper">
		<h3 style="text-align:center;">
			Emmortal Seo Details
		</h3>
		<div class="col-sm-12"
			style="margin-bottom: 20px; padding: 0 !important">

            <h1 id="csv_title" style="display: none;">Emmortal Seo Details</h1>
            <a href="/seomanage/bgedit" class="new_user" title="Change Background Image">Background Image</a>
		</div>

		<div class="row mt">
			<div class="col-md-12">
				<div class="content-panel" style="padding-top: 5px;">


                        <table class="table table-striped table-advance table-hover tbody userDetails datatable sortable" name="userDetails" id="userDetails">

						<thead>
							<tr class="show_rows">
								<td style="cursor: pointer; font-weight: bold;" class="hidden-phone"><i
									class="fa fa-bookmark"></i> Title</td>
								<td style="cursor: pointer; font-weight: bold;" class="hidden-phone"><i
									class="fa fa-bookmark"></i> Description</td>
                                <td style="cursor: pointer; font-weight: bold;" class="hidden-phone"><i
									class="fa fa-bookmark"></i> Seo image</td>
                                <td style="cursor: pointer; font-weight: bold;"><i
									class="fa fa-bookmark"></i> Favicon</td>
								<td style="cursor: pointer; font-weight: bold;"><i
									class="fa fa-bookmark"></i> Creation date</td>
							</tr>
						</thead>

						<tbody class="my_size">
							<?php if(!empty($seodata)){
								foreach($seodata as $key => $val)
					               { ?>

							<tr	class="manageAll catId show_rows">
								<td class="hidden-phone"><?php if(!empty($val['seopagetitle'])){
                                    echo strip_tags($val['seopagetitle']);} else{ echo "N/A"; }
                                    ?></td>
								<td class="hidden-phone email-width"><span class=""
									style=""><?php echo strtolower($val['seometadescription']); ?>
								</span></td>
                                <td class="hidden-phone profileImg"><span class="profileImg"
									style="padding: 5px; font-weight: bold;"><img src="<?php echo $val['seoOGimagepath'];?>"  height="100px" width="100px" />
								</span></td>
                                <td class="hidden-phone profileImg"><span class="profileImg"
									style="padding: 5px; font-weight: bold;"><img src="<?php echo $val['seoFaviconimagepath'];?>"  height="100px" width="100px" />
								</span></td>
                                <td class="hidden-phone"><?php echo $val['creationDate'];?></td>
							</tr>
							<tr id="hidden_tr" style="display: none;" class="for_search">
								<th style="border-bottom: 0px !important;">No records found</th>
							</tr>
							<?php }
                            }
							else
							{
							   echo "No records found...";
							}?>
						</tbody>
					</table>
				</div>
				<!-- /content-panel -->

			</div>
			<!-- /col-md-12 -->
		</div>
		<!-- /row -->

	</section>
	<!-- /wrapper -->

	<!--delete popup -->
<!--
	<section id="dynamicpagecreatepopup" class="popupFormForDynamicPage chang_PPopup_conta">
	 <div id="" class="chang_PPopup">
     <div class="tab-content" style="border:0px solid;width:490px;">
		<form class="form-popup" style="margin-top: 0px;" method="POST" action="/usermanage/userdelete" enctype="multipart/form-data">
			 <a class="close" href="javascript:void(0)" onclick="$('#dynamicpagecreatepopup').hide();" style="margin: 10px 10px 0 0px;"><i aria-hidden="true" class="fa fa-times"></i></a>
			<h2 class="form-login-heading">Delete User</h2>
			<div class="login-wrap" style="overflow:hidden;text-align:center;">
				<input type="hidden" name="hidden_id" value="" id="hidden_userid" class="hidden_id" />
				<h4 class="form-login-heading">Are you sure you want to delete this user?</h4>
				<div style="overflow:hidden;display:inline-block;">
                    <input type="button" class="popup_cancel" onclick="$('#dynamicpagecreatepopup').hide();" id="btn" value="CANCEL"/>
                    <input type="submit" class="popup_cancel" id="delUser" value="OK"/>
				</div>
			</div>
		</form>
     </div>/tab-content
     </div>
    </section>
-->
    <!-- /delete popup-->

</section>
<!-- /MAIN CONTENT -->

