<section id="main-content">
	<section class="wrapper">
		<h3 style="text-align:center;">
			Emmortal User Details
		</h3>
		<div class="col-sm-12"
			style="margin-bottom: 20px; padding: 0 !important">

			<h1 id="csv_title" style="display: none;">Emmortal User Details</h1>
			<a class="download-report export dwnload_csv" href="javascript:void(0)" download="Participant-Details.csv" title="Download CSV in excel">Download CSV</a>
				<a href="/usermanage/userbackupdet" class="user_backup" title="User backup details"><i class="fa fa-recycle fa-3x" aria-hidden="true"></i></a>


		</div>

		<div class="row mt">
			<div class="col-md-12">
				<div class="content-panel" style="padding-top: 5px;">

                       <div class="col-md-12" style="padding: 0px 10px;">
                            <!-- Search bar here -->
                            <div class="search-bar clearfix" style="margin-bottom: 10px">
                                <input class="form-control" id="registeredtableSearch" type="text" placeholder="Search here" name="search" style="width: 100%; height: 35px;">
                            </div>
                            <!-- Search bar end -->
                       </div>
				       <div class="col-md-12" style="padding: 0px 10px;">
                            <!-- No. of Users here -->
                            <div class="numberclasscheck" style="margin-bottom: 10px">Number Of User(s) :
                                <?php if(!empty($userdata)){
								    $user = count($userdata);
                                    echo $user;  } ?>
                            </div>
                            <!-- No. of Users end -->
                       </div>
                        <table class="table table-striped table-advance table-hover tbody userDetails datatable sortable" name="userDetails" id="userDetails">

						<thead>
							<tr class="show_rows">
								<td style="cursor: pointer; font-weight: bold;" class="hidden-phone"><i
									class="fa fa-bookmark"></i> Name</td>
								<td style="cursor: pointer; font-weight: bold;" class="hidden-phone"><i
									class="fa fa-bookmark"></i> Email</td>
                                <td style="cursor: pointer; font-weight: bold;" class="hidden-phone"><i
									class="fa fa-bookmark"></i> Profile image</td>
                                <td style="cursor: pointer; font-weight: bold;"><i
									class="fa fa-bookmark"></i> Registration Date</td>
								<td style="cursor: pointer; font-weight: bold;" class="sorttable_nosort"><i
									class="fa fa-bookmark"></i> Action</td>
							</tr>
						</thead>

						<tbody class="my_size">
							<?php if(!empty($userdata)){
								foreach($userdata as $key => $val)
					               { ?>

							<tr	class="manageAll catId show_rows">
								<td class="hidden-phone"><?php if(!empty($val['firstname']) || !empty($val['lastname'])){
                                    echo strip_tags($val['firstname'])." ".strip_tags($val['lastname']);} else{ echo "N/A"; }
                                    ?></td>
								<td class="hidden-phone email-width"><span class=""
									style=""><?php echo strtolower($val['emailid']); ?>
								</span></td>
                                <td class="hidden-phone profileImg"><span class="profileImg"
									style="padding: 5px; font-weight: bold;"><img src="<?php if (@getimagesize($val['profileimage'])) {
                    echo $val['profileimage'];
                } else {
                    echo "/image/profile-deafult-avatar.jpg";
                }?>"  height="100px" width="100px" /><!--(after src tag) onerror="this.src='<?php //echo $dynamicPath; ?>/template/demo.jpg'"-->
								</span></td>
                                <td class="hidden-phone"><span class=""
									style="width: 80%; display: inline-block;"><?php echo $val['signindate'];?>
								</span></td>

								<input type="hidden"  class="hidden_class" value="<?php echo $val['userid']; ?>" />
								<td class="sorttable_nosort">

                                    <a href="<?php echo '/usermanage/useredit/'.$val['userid']; ?>" title="Edit user details">
                                            <button class="btn btn-primary btn-xs edit_user">
                                                <i class="fa fa-pencil" aria-hidden="true"></i>
                                            </button>
                                    </a>
									        <button class="btn btn-danger btn-xs dlt_nom deleteUser" title="Delete user">
										        <i class="fa fa-trash-o"></i>
									        </button> <br/>

								</td>
							</tr>
							<tr id="hidden_tr" style="display: none;" class="for_search">
								<th style="border-bottom: 0px !important;">No records found</th>
							</tr>
							<?php }
                            }
							else
							{
							   echo "No records found...";
							}?>
						</tbody>
					</table>
				</div>
				<!-- /content-panel -->

			</div>
			<!-- /col-md-12 -->
		</div>
		<!-- /row -->

	</section>
	<!-- /wrapper -->

	<!--delete popup -->
	<section id="dynamicpagecreatepopup" class="popupFormForDynamicPage chang_PPopup_conta">
	 <div id="" class="chang_PPopup">
     <div class="tab-content" style="border:0px solid;width:490px;">
		<form class="form-popup" style="margin-top: 0px;" method="POST" action="/usermanage/userdelete" enctype="multipart/form-data">
			 <a class="close" href="javascript:void(0)" onclick="$('#dynamicpagecreatepopup').hide();" style="margin: 10px 10px 0 0px;"><i aria-hidden="true" class="fa fa-times"></i></a>
			<h2 class="form-login-heading">Delete User</h2>
			<div class="login-wrap" style="overflow:hidden;text-align:center;">
				<input type="hidden" name="hidden_id" value="" id="hidden_userid" class="hidden_id" />
				<h4 class="form-login-heading">Are you sure you want to delete this user?</h4>
				<div style="overflow:hidden;display:inline-block;">
                    <input type="button" class="popup_cancel" onclick="$('#dynamicpagecreatepopup').hide();" id="btn" value="CANCEL"/>
                    <input type="submit" class="popup_cancel" id="delUser" value="OK"/>
				</div>
			</div>
		</form>
     </div><!--/tab-content-->
     </div>
    </section><!-- /delete popup-->

</section>
<!-- /MAIN CONTENT -->
