<?php
$controller = strtolower($controller);
$action = strtolower($action);
$t = time();
switch ($controller) {
	case 'profile':
		switch ($action) {   
             case 'showprofile':
                $this->headLink()
                    ->prependStylesheet($this->basePath() . '/css/album/like.css?version=' . $t)
                    ->prependStylesheet($this->basePath() . '/css/profile/profile.css?version=' . $t)
                    ->prependStylesheet($this->basePath() . '/css/profile/searchfriends.css?version=' . $t);
                 break;

             case 'newsfeed':
                $this->headLink()
                   ->prependStylesheet($this->basePath() . '/css/Album/termsconditions.css?version=' . $t);
             break;
		}
		break;
        case 'account':
        switch ($action) {   
             case 'myaccount':
                $this->headLink()
                    ->prependStylesheet($this->basePath() . '/css/profile/profile.css?version=' . $t);
                 break;
        }
        break;
    case 'settings':
        switch ($action) {
             case 'general':
                $this->headLink()
                    ->prependStylesheet($this->basePath() . '/css/profile/profile.css?version=' . $t);
                 break;
        }
        break;
	default:
		break;
}
echo $this->headLink()
      ->prependStylesheet($this->basePath() . '/css/profile/profilenavbar.css?version=' . $t)
      ->prependStylesheet($this->basePath() . '/css/Album/design.css?version=' . $t)
       ->prependStylesheet($this->basePath() . '/css/Album/main.css?version=' . $t)
       ->prependStylesheet($this->basePath() . '/css/Album/style.css?version=' . $t)
        ->prependStylesheet($this->basePath() . '/css/Album/navbar.css?version=' . $t)
        ->prependStylesheet($this->basePath() . '/css/bootstrap/bootstrap.min.css?version=' . $t)
        ->prependStylesheet($this->basePath() . '//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css')
    	->prependStylesheet($this->basePath() . '//fonts.googleapis.com/css?family=Oxygen:400,700' );
?>
